### PR TITLE
Add ?gui and ?console conditionals

### PR DESCRIPTION
**Pull request by GWRon**

### CODE REVIEW

**Comment by GWRon** [comment]
Is there a reason to not accept PRs like this? If so - it would be nice to know about them.

**Comment by GWRon** [comment]
Bump.

What speaks again such PRs ?

**Comment by braxtonrivers** [comment]
this is a really good idea, plus it also includes a fix for the double ToLower() that is accidentally present.

**Review by braxtonrivers — APPROVED** [review]
this is a really good idea, plus it also includes a fix for the double ToLower() that is accidentally present.

**Pull request merged**
