### PR TITLE
Index operator overloading

### PR DESCRIPTION
**Pull request by HurryStarfish**
I figured it would make sense to add index operator overloading to BlitzMax. This feature allows user-defined types to support indexed element access via brackets (`[]`), just like the built-in arrays, pointers and strings do.
Like all operator overloading, it should be used conservatively, but this should be a useful addition for collection types such as arrays, lists or maps.

This pull request adds two new overloadable operators: 

- `Method Operator []` is the index operator. It should take one or more *indices* as parameters and return the corresponding *element*.
- `Method Operator []=` is the index assignment operator. It should take one or more *indices* and the to-be-assigned *element* as parameters and not return anything.

<br>

As an example, a wrapper type for an array that automatically grows when accessing an out-of-bounds index can be written like this:
```BlitzMax
SuperStrict
Framework BRL.StandardIO

Type TDynamicIntArray
	Private
	
	Field array:Int[]
	Field startIndex:Int = 0
	
	Public
	
	Method Operator [] :Int(index:Int)
		If index < startIndex Or index >= startIndex + array.length Then Return 0
		Return array[index - startIndex]
	End Method
	
	Method Operator []= (index:Int, value:Int)
		If index < startIndex Then
			array = array[index - startIndex..]
			startIndex = index
		Else If index >= startIndex + array.length Then
			array = array[..index - startIndex + 1]
		End If
		' ^ it's inefficient to grow arrays like this, but it's just a simple example
		array[index - startIndex] = value
	End Method
End Type


Local a:TDynamicIntArray = New TDynamicIntArray
a[-1] = -1 ' this calls Operator []=
a[2] = 2   ' this calls Operator []=
a[4] = 4   ' this calls Operator []=
For Local i:Int = -2 To 5
	Print i + ": " + a[i] ' this calls Operator []
Next
```

Indices can be of any type; they do not need to be `Int`:
```BlitzMax
SuperStrict
Framework BRL.StandardIO
Import BRL.Map

Type TMapWithOperators Extends TMap ' extending TMap to keep the example simple
	Method Operator [] :Object(key:Object)
		Return ValueForKey(key)
	End Method
	
	Method Operator []= (key:Object, value:Object)
		Insert key, value
	End Method
End Type

Local map:TMapWithOperators = New TMapWithOperators

' insert an element
map["hello"] = "world"

' retrieve the element
Print map["hello"].ToString()
```

And like the built-in multidimensional arrays, user-defined types can also support multiple indices:
```BlitzMax
SuperStrict
Framework BRL.StandardIO

Type TMultidimTest
	Method Operator [] :String(index0:Int, index1:Int, index2:Float)
		Return "Element at [" + index0 + ", " + index1 + ", " + index2 + "]"
	End Method
End Type

Local x:TMultidimTest = New TMultidimTest
Print x[1, 2, 3]
```

<br>

Limitations:
- Since user-defined operators are methods, elements of user-defined types cannot directly be used as `Var` or `Varptr` arguments (i.e. you cannot do `Varptr(x[y])`). This can be worked around by storing the element in a variable first.
- It is not yet possible to overload the slice operator (i.e. `array[3..5]`). I already have an idea how to do this though.

### CODE REVIEW

**Comment by GWRon** [comment]
Being able to do a `vars["name"] = "test"` would really be a handy addition (reminds me on many scripting languages which offer this). The limitation of not being able to pass it to as var-param to functions (`setItem(i, vars["name"])`) is a limitation which should be tackled - as it makes the whole thing "inconsistent". Behaviour should not alter or be blocked if it "normally" (eg passing `array[i]`) works.

If Brucey sees a way to allow both then yay, add it! Else you somehow need to clarify the limitations.


@ adding / assigning elements
For arrays we could do 
```
local arr:int[] = [1,2,3]
arr :+ [4,5]
```

When overloading the "[]" operator we should think of overloading the "+" operator too - to keep consistent with current array operator behaviour

**Comment by woollybah** [comment]
Looks good. Thanks :-)

I agree with  @GWRon about also supporting array addition.
Limitations seem fine, assuming it will raise an error if you try to use it inappropriately?

**Comment by GWRon** [comment]
I see an potential issue with the "array addition".

@HurryStarfish had an example with the "TMapWithOperators". `TMap` requires a key for each "to add" value/object. An `map["hello"] = "world"` works as it has key and value. Now `map :+ ["world"]` cannot work as the desired key is missing. Any Ideas?

It would of course work for linked lists like `TList` as they do not required the additional information.

**Comment by woollybah** [comment]
Ah yes, of course, I'm thinking of it like arrays, but it's not that... it's about "indexed" access to some data.
Never mind about the addition, it doesn't make sense here :-)

**Comment by HurryStarfish** [comment]
Well, `[]` and `+` are separate operators, so each type can just support the ones that make sense for it.

@GWRon 
> The limitation of not being able to pass it to as var-param to functions (setItem(i, vars["name"])) is a limitation which should be tackled

Unfortunately, that's is a difficult technical problem.
Internally, `Var` parameters are basically just pointers. If you write
```BlitzMax
Function F(x:Int Var)
	x :+ 1
End Function
```
then it gets compiled to the equivalent of
```BlitzMax
Function F(x:Int Ptr)
	x[0] :+ 1
End Function
```
If you have an array `Local array:Int[]` and you want to call `F(array[x])`, that's not a problem, because the compiler knows how to turn an array element into an `Int Ptr` that can be passed to `F`. It compiles `array[x]` into the equivalent of `Varptr(array[x])` (or `Int Ptr(Byte Ptr(array)) + x`).
But overloaded operators are methods, and you can't have an `Int Ptr` automatically call a method when read from or written to. The code in `F` (`x[0] :+ 1`) simply reads and writes to the memory location that `x` points to.
That's is why this limitation exists.

I don't think there is a good solution for this.
For example, one approach might be to have bcc compile multiple versions of function/methods with `Var` parameters: a "pointer" version and a "method" version for every `Var` parameter. But then you wouldn't be able to convert functions into function pointers anymore, and you'd run into problems with reflection.
Another approach would be wrapping *all* `Var` parameter access in method calls, even the ones for simple variables or array elements. But that would break compatibility in several places and have a negative impact on speed.

Fortunately, you can work around this easily with a local variable.
For example, instead of
```
Local a:TDynamicIntArray = New TDynamicIntArray
' ...
F(a[x])
```
you can do
```
Local a:TDynamicIntArray = New TDynamicIntArray
' ...
Local element:Int = a[x]
F(element)
a[x] = element
```
The difference is that a[x] will be updated after `F` has returned, not immediately when `F` writes to its `Var` parameter. But usually that doesn't matter.

**Comment by HurryStarfish** [comment]
> Now map :+ ["world"] cannot work as the desired key is missing. Any Ideas?

Well, that would be trying to add an array to a map, which doesn't make much sense. With builtin arrays, you can do `myIntArray + [5]` because `[5]` is also an array, and the `+` operator adds two arrays together.

You could certainly define a `+` operator between two maps, which returns a new map that contains the entries of both of them. But this might not be a good idea, because if there was an entry with the same key in both maps, then one of those two entries would have to "win" and overwrite the other. That's a "gotcha" that's not obvious from an innocent-looking `+`, so it could easily cause bugs in people's code.

**Comment by GWRon** [comment]
In an addition of two maps...the right side wins over the left.
Same as it evaluates stuff from left to right:
If AddOne() > 1 and AddOne() > 2 ...
Means most right gets executed last. Means in an addition of maps the right part comes last too. Skip mathematical theory there and do not allow switching summands :-)


Regarding adding of elements. One could allow it if elements are evaluated:

Map :+ [key, object, key, object...]

But this is surely a bit hacky/dirty/ambiguous as it then is inconsistent to array adding.

Hmm. Just hoped for a way to have all the containers have similar operators so that the underlaying collection algorithms are the only difference.

No big thing to worry about.


@HurryStarfish 
Thanks for your continuous work to give me some insights on how the more advanced stuff works.

**Pull request merged**
